### ISSUE TITLE
Can't open files from File Group in Explorer bar

### ISSUE THREAD

**Issue by ghost** [rioj7/fileGroup#8] opened 2022-08-26 11:14 UTC
Update  -
My mistake -- I misunderstood the Readme -- the buttons and context menu are on the File Group, not on the individual files.
Good extension.
// ----------------------------------------
Win10 Pro x64
VS Code 17.0.2
File Group 1.0.2

In the Readme:
"You can open the group with the buttons on the group item and with the context menu of the group item."

Neither of these show up for me in the Explorer bar -- the buttons on the group item, nor the context menu on the group item.

Great idea for an extension, I just can't seem to get it to work.

**Comment by rioj7** [comment] 2022-08-27 13:01
@cbates- If the problem is solved you can close the issue

**Closed as completed** 2022-08-28 12:44 UTC
